Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [1]:
import numpy as np

In [2]:
# List of functions explained 
function1 = np.reshape
function2 = np.vstack
function3 = np.hsplit
function4 = np.squeeze
function5 = np.cross

## Function 1 - np.reshape

A very useful function for changing the shape of a numpy array.
It takes the original array and the new shape (as a pair of tuple) as arguements and returns a new numpy array with the new shape.

In [3]:
arr = np.array([1,2,3,4])
np.reshape(arr,(2,2))

array([[1, 2],
       [3, 4]])

Converted a 1d numpy array into a 2d numpy array (not in place)

In [4]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

numpy.arange created a 1d numpy array which was then converted into a 2d numpy array by reshape method.

In [5]:
arr = np.arange(10)
np.reshape(arr,(2,2))

ValueError: cannot reshape array of size 10 into shape (2,2)

It breaks when the number of elements present in the array is not equal to the number of elements required in the converted array.

It can be solved by passing a valid shape to reshape method. A valid shape is the one that will contain exactly the same number of elements as that of the original array.

This function is very useful if you want to change the shape of an array not in place.

## Function 2 -  np.vstack

Stack arrays in sequence vertically (row wise).

In [6]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

Stacked the numpy arrays 'a' and 'b' and returned a new array without affecting the original arrays.

In [7]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
c = np.array([[2], [3], [4]])
np.vstack((a,b,c))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4],
       [2],
       [3],
       [4]])

Stacked the 3*1 numpy arrays 'a', 'b' & 'c' and returned a new 5*1 array without affecting the original arrays.

In [8]:
a = np.array([[1], [2], [3]])
b = np.array([[2,3], [3,4], [4,5],[5,6]])
np.vstack((a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 2

It breaks when the dimensions of the arrays don't match.

It can be fixed by passing the arrays of same dimensions.

It should be used whenever there is a need of vertical concatenation of two or more arrays.

## Function 3 - np.hsplit

Using hsplit, we can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur.

It takes two objects as arguements:
1) The original array (which is to be splitted horizontally)
2) The index about which the array to splitted

The original array is always split along the second axis regardless of the array dimension.

In [9]:
x = np.arange(16.0).reshape(4, 4)
np.hsplit(x,2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

Splitted a 4 * 4 numpy array into two 4 * 2 numpy arrays

In [10]:
x = np.arange(8.0).reshape(2, 2, 2)
np.hsplit(x, 2)

[array([[[0., 1.]],
 
        [[4., 5.]]]),
 array([[[2., 3.]],
 
        [[6., 7.]]])]

With a higher dimensional array the split is still along the second axis.

In [11]:
x = np.arange(16.0).reshape(4, 4)
np.split(x,8)

ValueError: array split does not result in an equal division

The index passed as parameter to the hsplit method should be within range of the original array's second axis and the splitted array should be equally divided.

It can be solved by giving a valid (within range) index to the hsplit method.
e.g. for a 4 * 4 numpy array, only the values {1,2,4} are valid. 3 is not valid as it will not result in equally divided arrays and any value greater than 4 is not valid because it will be out of range.

A useful function if you want to split an array along the second axis.

## Function 4 - np.squeeze

Remove axes of length one from the given array (not in place).
It takes two objects as parameters:
1) The array fromw which the axes to be removed
2) The axis which will be removed

The input array, but with all or a subset of the dimensions of length 1 removed. This is always input array itself or a view into input array. If all axes are squeezed, the result is a 0d array and not a scalar.

In [12]:
x = np.arange(16).reshape(1,16,1)
np.squeeze(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Removed all the subsets of dimension 1

In [13]:
x = np.arange(16).reshape(1,16,1)
np.squeeze(x,0)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

Removed the subset of dimension 1 at the axis 0 (as specified)

In [14]:
x = np.arange(16).reshape(1,16,1)
np.squeeze(x,1)

ValueError: cannot select an axis to squeeze out which has size not equal to one

Only the size of axis 0 and 2 is 1. The size of axis 1 is 16 and hence it cannot select an axis to squeeze out which has size not equal to one.

Pass only such a axis whose size is equal to one or pass nothing in place of axis then it will automatically detect and delete all such axes.

A very useful function which will be used whenever we need to remove axes of size 1

## Function 4 - np.cross

numpy.cross(a, b, axisa=-1, axisb=-1, axisc=-1, axis=None)
The cross product of a and b in R^3 is a vector perpendicular to both a and b. If a and b are arrays of vectors, the vectors are defined by the last axis of a and b by default, and these axes can have dimensions 2 or 3. Where the dimension of either a or b is 2, the third component of the input vector is assumed to be zero and the cross product calculated accordingly. In cases where both input vectors have dimension 2, the z-component of the cross product is returned.

In [15]:
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

Returned the vector cross product of the vectors x and y.

In [16]:
x = [1, 2]
y = [4, 5, 6]
np.cross(x,y)

array([12, -6, -3])

When an element is missing, it assumes that zero.

In [17]:
x = [1,2,3,4]
y = [4,5,6]
np.cross(x,y)

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

The dimensions must be 2 or 3. Anything >3 or <2 is not compatible.

It can be fixed by passing the vectors of dimensions exactly 2 or 3.

Very usefult function in order to perform cross product on two vectors.

## Conclusion

I went through the official numpy tutorial website. There is a lot of methods. I tried to explain some of them.

## Reference Links
Useful links:

* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* reshape : https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy.reshape
* vstack  : https://numpy.org/doc/stable/reference/generated/numpy.vstack.html#numpy.vstack
* hsplit  : https://numpy.org/doc/stable/reference/generated/numpy.hsplit.html#numpy.hsplit
* squeeze : https://numpy.org/doc/stable/reference/generated/numpy.squeeze.html#numpy.squeeze
* cross   : https://numpy.org/doc/stable/reference/generated/numpy.cross.html#numpy.cross

In [18]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "tusharg895/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/tusharg895/numpy-array-operations


'https://jovian.ai/tusharg895/numpy-array-operations'

In [ ]:
jovian.submit(assignment="zero-to-pandas-a2")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
